// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg/msg.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// NewsItem identifier for request.
type ID struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0f0a1b324c95b77, []int{0}
}

func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (m *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(m, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

// NewsItem itself.
type NewsItem struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Header               string   `protobuf:"bytes,2,opt,name=Header,proto3" json:"Header,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewsItem) Reset()         { *m = NewsItem{} }
func (m *NewsItem) String() string { return proto.CompactTextString(m) }
func (*NewsItem) ProtoMessage()    {}
func (*NewsItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0f0a1b324c95b77, []int{1}
}

func (m *NewsItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewsItem.Unmarshal(m, b)
}
func (m *NewsItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewsItem.Marshal(b, m, deterministic)
}
func (m *NewsItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewsItem.Merge(m, src)
}
func (m *NewsItem) XXX_Size() int {
	return xxx_messageInfo_NewsItem.Size(m)
}
func (m *NewsItem) XXX_DiscardUnknown() {
	xxx_messageInfo_NewsItem.DiscardUnknown(m)
}

var xxx_messageInfo_NewsItem proto.InternalMessageInfo

func (m *NewsItem) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *NewsItem) GetHeader() string {
	if m != nil {
		return m.Header
	}
	return ""
}

func (m *NewsItem) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// Response for NewsItem request with error.
type Response struct {
	Item                 *NewsItem `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Error                string    `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0f0a1b324c95b77, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetItem() *NewsItem {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*ID)(nil), "msg.ID")
	proto.RegisterType((*NewsItem)(nil), "msg.NewsItem")
	proto.RegisterType((*Response)(nil), "msg.Response")
}

func init() { proto.RegisterFile("msg/msg.proto", fileDescriptor_d0f0a1b324c95b77) }

var fileDescriptor_d0f0a1b324c95b77 = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x2d, 0x4e, 0xd7,
	0xcf, 0x2d, 0x4e, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2d, 0x4e, 0x57, 0x12,
	0xe1, 0x62, 0xf2, 0x74, 0x11, 0xe2, 0x03, 0x91, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0x4c,
	0x9e, 0x2e, 0x4a, 0x6e, 0x5c, 0x1c, 0x7e, 0xa9, 0xe5, 0xc5, 0x9e, 0x25, 0xa9, 0xb9, 0xe8, 0x72,
	0x42, 0x62, 0x5c, 0x6c, 0x1e, 0xa9, 0x89, 0x29, 0xa9, 0x45, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c,
	0x41, 0x50, 0x9e, 0x90, 0x10, 0x17, 0x8b, 0x4b, 0x62, 0x49, 0xa2, 0x04, 0x33, 0x58, 0x14, 0xcc,
	0x56, 0x72, 0xe6, 0xe2, 0x08, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x52, 0xe4, 0x62,
	0xc9, 0x2c, 0x49, 0xcd, 0x05, 0x9b, 0xc4, 0x6d, 0xc4, 0xab, 0x07, 0x72, 0x08, 0xcc, 0x92, 0x20,
	0xb0, 0x94, 0x90, 0x08, 0x17, 0x6b, 0x6a, 0x51, 0x51, 0x3e, 0xcc, 0x64, 0x08, 0x27, 0x89, 0x0d,
	0xec, 0x5c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x98, 0x51, 0x17, 0xbf, 0x00, 0x00,
	0x00,
}
